project:
  type: website  
  output-dir: docs

website:
  title: "bibtex_2_website_qmds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications/index.qmd
        text: Publications
    tools:
      - icon: github
        menu:
          - text: Repository
            href:  https://github.com/jebyrnes/bibtex_2_website_qmds
          - text: Report a Bug
            href:  https://github.com/jebyrnes/bibtex_2_website_qmds/issues



format:
  html:
    theme: morph
    toc: true